package cmd

import (
	_ "github.com/sikalabs/slr/cmd/allocate_100mb"
	_ "github.com/sikalabs/slr/cmd/break_line"
	_ "github.com/sikalabs/slr/cmd/check_docker_credentials"
	_ "github.com/sikalabs/slr/cmd/client_ip_web_server"
	_ "github.com/sikalabs/slr/cmd/copy_from_cloud"
	_ "github.com/sikalabs/slr/cmd/copy_to_cloud"
	_ "github.com/sikalabs/slr/cmd/cpu_load_generator"
	_ "github.com/sikalabs/slr/cmd/dela"
	_ "github.com/sikalabs/slr/cmd/du_gitlab_tls_update"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/du_notification"
	_ "github.com/sikalabs/slr/cmd/example"
	_ "github.com/sikalabs/slr/cmd/get_gps_info_from_jpg"
	_ "github.com/sikalabs/slr/cmd/get_helm_chart_version_from_repo"
	_ "github.com/sikalabs/slr/cmd/get_jwt_from_oidc"
	_ "github.com/sikalabs/slr/cmd/get_nodes_from_kubernetes"
	_ "github.com/sikalabs/slr/cmd/get_tls_from_kubernetes"
	_ "github.com/sikalabs/slr/cmd/gitlab_create_branch"
	_ "github.com/sikalabs/slr/cmd/gitlab_create_merge_request"
	_ "github.com/sikalabs/slr/cmd/gitlab_merge_merge_request"
	_ "github.com/sikalabs/slr/cmd/gitlab_update_file"
	_ "github.com/sikalabs/slr/cmd/gitlab_update_file_pull_request"
	_ "github.com/sikalabs/slr/cmd/gitlab_update_files"
	_ "github.com/sikalabs/slr/cmd/gojekyll"
	_ "github.com/sikalabs/slr/cmd/install_du_gitlab_tls_update"
	_ "github.com/sikalabs/slr/cmd/install_restart_eno1_systemd"
	_ "github.com/sikalabs/slr/cmd/kubeconfig_from_vault"
	_ "github.com/sikalabs/slr/cmd/kubernetes_homepage"
	_ "github.com/sikalabs/slr/cmd/list_mimio_s3_bucket"
	_ "github.com/sikalabs/slr/cmd/list_mimio_s3_buckets"
	_ "github.com/sikalabs/slr/cmd/memory_usage"
	_ "github.com/sikalabs/slr/cmd/ondrejsika"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/add_ad_to_readme"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/add_claude_md_from_sikalabs_slu"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/backup_file_ducr"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/example"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/export_trainingcrm_attendees"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/prvninakup_notification"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/reverse_fotoskoda_film_photos"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/set_exif_time"
	_ "github.com/sikalabs/slr/cmd/ondrejsika/stegosay"
	_ "github.com/sikalabs/slr/cmd/parse_jwt"
	_ "github.com/sikalabs/slr/cmd/redis_set_large_data"
	_ "github.com/sikalabs/slr/cmd/render_template"
	_ "github.com/sikalabs/slr/cmd/render_templates"
	_ "github.com/sikalabs/slr/cmd/restart_eno1"
	"github.com/sikalabs/slr/cmd/root"
	_ "github.com/sikalabs/slr/cmd/save_env_to_file"
	_ "github.com/sikalabs/slr/cmd/scan_network"
	_ "github.com/sikalabs/slr/cmd/s3_backups_cleanup"
	_ "github.com/sikalabs/slr/cmd/s3_bucket_size"
	_ "github.com/sikalabs/slr/cmd/scr"
	_ "github.com/sikalabs/slr/cmd/servers_md"
	_ "github.com/sikalabs/slr/cmd/static_hash_tagger"
	_ "github.com/sikalabs/slr/cmd/test_clisso_cli"
	_ "github.com/sikalabs/slr/cmd/time_exporter"
	_ "github.com/sikalabs/slr/cmd/training"
	_ "github.com/sikalabs/slr/cmd/training/az_training_user_creds"
	_ "github.com/sikalabs/slr/cmd/training/kubernetes"
	_ "github.com/sikalabs/slr/cmd/training/kubernetes/connect"
	_ "github.com/sikalabs/slr/cmd/training/load_kubeconfig"
	_ "github.com/sikalabs/slr/cmd/training/openshift_creds"
	_ "github.com/sikalabs/slr/cmd/training/openshift_pull_secret"
	_ "github.com/sikalabs/slr/cmd/training/otp"
	_ "github.com/sikalabs/slr/cmd/training/save_kubeconfig"
	_ "github.com/sikalabs/slr/cmd/training/setup_git"
	_ "github.com/sikalabs/slr/cmd/tree"
	_ "github.com/sikalabs/slr/cmd/validate_jwt"
	_ "github.com/sikalabs/slr/cmd/vault_copy_file_from_vault"
	_ "github.com/sikalabs/slr/cmd/vault_copy_file_to_vault"
	_ "github.com/sikalabs/slr/cmd/vault_filler"
	_ "github.com/sikalabs/slr/cmd/vault_init_unseal"
	_ "github.com/sikalabs/slr/cmd/version"
	_ "github.com/sikalabs/slr/cmd/vibe"
	"github.com/spf13/cobra"
)

func Execute() {
	cobra.CheckErr(root.Cmd.Execute())
}
