render:
	slr render-template \
		--template src/templates/README.md.gotemplate \
		--output output/README.generated.md \
		--data project=./src/data/project.yaml \
		--data users=./src/data/users.yaml
	cat output/README.generated.md
